name: Docker Image CI

on:
  push:
    branches:
      - MARK-v18.03r73-mesh

  pull_request:
    branches:
      - MARK-v18.03r73-mesh

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 7 * * 3'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        context: ./
        file: ./Dockerfile
        tags: solutionsoft/timemachine-sidecar:build-v18.03r73-mesh
