name: Docker Image CI

on:
  push:
    branches: [ "mesh" ]
    
  pull_request:
    branches: [ "mesh" ]

  schedule:
    - cron: "0 10 * * 1" # every Monday

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Define build timestamp and release info
      run: |
        echo "timestamp=$(date +%Y%m%d)" >> $GITHUB_ENV
        cat dist/etc/release.info >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        context: ./
        file: ./Dockerfile
        tags: solutionsoft/timemachine-sidecar:latest-mesh, solutionsoft/timemachine-sidecar:build-${{ env.timestamp }}-mesh, solutionsoft/timemachine-sidecar:release-${{ env.release }}-mesh
